In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from lazypredict.Supervised import LazyClassifier # type: ignore

In [ ]:
train_path = "C:/Users/admin/Desktop/self-healing-ml/self-healing-model/data/processed/online_shoppers_intention_train.csv"
test_path = "C:/Users/admin/Desktop/self-healing-ml/self-healing-model/data/processed/online_shoppers_intention_test.csv"

In [ ]:
train = pd.read_csv(train_path)
test = pd.read_csv(test_path)

X_train = train.drop(columns=["Revenue"])
y_train = train["Revenue"]

X_test = test.drop(columns=["Revenue"])
y_test = test["Revenue"]

In [ ]:
clf = LazyClassifier(verbose=0, ignore_warnings=True)
models, predictions = clf.fit(X_train, X_test, y_train, y_test)

In [11]:
print(type(models))

<class 'pandas.core.frame.DataFrame'>

In [16]:
models.sort_values(by=["Accuracy","Time Taken"],ascending=[False,True])

                               Accuracy  ...  Time Taken
Model                                    ...
RandomForestClassifier         0.894972  ...    0.985302
XGBClassifier                  0.888483  ...    0.136470
AdaBoostClassifier             0.887672  ...    0.610063
ExtraTreesClassifier           0.885645  ...    0.649670
SVC                            0.882401  ...    1.683354
BaggingClassifier              0.880373  ...    0.532712
LogisticRegression             0.870235  ...    0.040330
CalibratedClassifierCV         0.870235  ...    0.166709
LinearDiscriminantAnalysis     0.869019  ...    0.066247
LinearSVC                      0.868613  ...    0.051674
SGDClassifier                  0.868208  ...    0.068467
KNeighborsClassifier           0.864558  ...    2.849692
RidgeClassifierCV              0.864152  ...    0.039251
RidgeClassifier                0.864152  ...    0.042145
DecisionTreeClassifier         0.851176  ...    0.116619
ExtraTreeClassifier            0.847526  ...    0.016625
BernoulliNB                    0.844688  ...    0.033261
LabelPropagation               0.834550  ...    3.233574
LabelSpreading                 0.834550  ...    4.228433
DummyClassifier                0.833333  ...    0.033327
Perceptron                     0.829684  ...    0.027816
NearestCentroid                0.810219  ...    0.034941
PassiveAggressiveClassifier    0.803731  ...    0.036163
GaussianNB                     0.731549  ...    0.033809
QuadraticDiscriminantAnalysis  0.645985  ...    0.033367

[25 rows x 7 columns]

In [17]:
models.sort_values(by=["Time Taken"],ascending=[True])

                               Accuracy  ...  Time Taken
Model                                    ...
ExtraTreeClassifier            0.847526  ...    0.016625
Perceptron                     0.829684  ...    0.027816
BernoulliNB                    0.844688  ...    0.033261
DummyClassifier                0.833333  ...    0.033327
QuadraticDiscriminantAnalysis  0.645985  ...    0.033367
GaussianNB                     0.731549  ...    0.033809
NearestCentroid                0.810219  ...    0.034941
PassiveAggressiveClassifier    0.803731  ...    0.036163
RidgeClassifierCV              0.864152  ...    0.039251
LogisticRegression             0.870235  ...    0.040330
RidgeClassifier                0.864152  ...    0.042145
LinearSVC                      0.868613  ...    0.051674
LinearDiscriminantAnalysis     0.869019  ...    0.066247
SGDClassifier                  0.868208  ...    0.068467
DecisionTreeClassifier         0.851176  ...    0.116619
XGBClassifier                  0.888483  ...    0.136470
CalibratedClassifierCV         0.870235  ...    0.166709
BaggingClassifier              0.880373  ...    0.532712
AdaBoostClassifier             0.887672  ...    0.610063
ExtraTreesClassifier           0.885645  ...    0.649670
RandomForestClassifier         0.894972  ...    0.985302
SVC                            0.882401  ...    1.683354
KNeighborsClassifier           0.864558  ...    2.849692
LabelPropagation               0.834550  ...    3.233574
LabelSpreading                 0.834550  ...    4.228433

[25 rows x 7 columns]